[[redirects]]
  from = "/disgen/*"
  to = "/disgen/:splat"
  status = 200
  force = true

[[headers]]
  for = "/disgen/*"
  [headers.values]
    WWW-Authenticate = "Basic realm=\"Privat släktforskning\""
    Basic-Auth = "stefan:eliasson1964"
